version: 0.0
os: linux 

files:
  - source: /
    destination: /opt/testapp
    overwrite: yes

permissions:
  - object: /opt/testapp/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh 
      timeout: 60
      runas: ubuntu